### PR TITLE
fix: compilation error when using _BLE_TRACE

### LINKED ISSUE #355: Compilation failed when _BLE_TRACE_ enabled
```
.pio/libdeps/nano_33_iot/ArduinoBLE/src/utility/L2CAPSignaling.cpp: In member function 'virtual void L2CAPSignalingClass::handleSecurityData(uint16_t, uint8_t, uint8_t*)':
.pio/libdeps/nano_33_iot/ArduinoBLE/src/utility/L2CAPSignaling.cpp:233:21: error: 'X' was not declared in this scope
     btct.printBytes(X,16);
                     ^
.pio/libdeps/nano_33_iot/ArduinoBLE/src/utility/L2CAPSignaling.cpp:235:21: error: 'Y' was not declared in this scope
     btct.printBytes(Y,16);
                     ^
.pio/libdeps/nano_33_iot/ArduinoBLE/src/utility/L2CAPSignaling.cpp: In member function 'virtual void L2CAPSignalingClass::smCalculateLTKandConfirm(uint16_t, uint8_t*)':
.pio/libdeps/nano_33_iot/ArduinoBLE/src/utility/L2CAPSignaling.cpp:416:19: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
     for(int i=0; i<sizeof(Eb); i++){
                  ~^~~~~~~~
*** [.pio/build/nano_33_iot/lib42d/ArduinoBLE/utility/L2CAPSignaling.cpp.o] Error 1
```

### PR DESCRIPTION
**Pull request by FidelSch**
Now correctly acceses the existing variables and uses an unsigned int for size comparison

fixes #355

### CODE REVIEW

File: src/utility/L2CAPSignaling.cpp [hunk 1]
```diff
@@ -413,7 +413,7 @@ void L2CAPSignalingClass::smCalculateLTKandConfirm(uint16_t handle, uint8_t expe
     // Send our confirmation value to complete authentication stage 2
     uint8_t ret[17];
     ret[0] = CONNECTION_PAIRING_DHKEY_CHECK;
-    for(int i=0; i<sizeof(Eb); i++){
+    for(uint i=0; i<sizeof(Eb); i++){
```
Comment (fpistm) [inline src/utility/L2CAPSignaling.cpp:416]:
```suggestion
    for(uint32_t i=0; i<sizeof(Eb); i++){
```

**Review by fpistm — CHANGES_REQUESTED** [review]

**Review by fpistm — APPROVED** [review]
Tanks @FidelSch
